languageCode = "en"
languageName = "English"
weight = 1
title = "DiagNet"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Welcome to DiagNet's website, a diploma thesis that aims to make Test-Driven-Networking not only possible, but also easy."

[params.author]
name = "DiagNet"
image = "https://github.com/DiagNet.png"
email = "diagnet.cloning895@passmail.net"
headline = "Test-Driven-Networking made easy"
bio = "A diploma thesis that aims to make Test-Driven-Networking not only possible, but also easy."
links = [
  { email = "mailto:diagnet.cloning895@passmail.net" },
  { github = "https://github.com/DiagNet" },
  { instagram = "https://instagram.com/" },
]
